package:
    name: pco_rclient
    version: "{{ load_setup_py_data().version }}"

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - requests
        - pyzmq

build:
    noarch: python
    number: 1

about:
    home: https://github.com/paulscherrerinstitute/pco_rclient
    summary: "Rest client for the lib_cpp_h5_writer / pco writer."
