package:
    name: pco_rclient
    version: "{{ load_setup_py_data().version }}"

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - requests

build:
    noarch: python
    number: 0

about:
    home: https://github.com/paulscherrerinstitute/pco_rclient
    summary: "Rest client script for the pco writer."
